### ISSUE TITLE
error on wwindows 10: ImportError: ('Unable to load OpenGL library', "Could not find module 'OSMesa' (or one of its dependencies).

### ISSUE THREAD

**Issue by linhcentrio** [postech-ami/MultiTalk#4]
> (D:\Talking_head\MultiTalk-Code\venv) D:\Talking_head\MultiTalk-Code>scripts\demo.bat multi
Traceback (most recent call last):
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\osmesa.py", line 22, in GL
    return ctypesloader.loadLibrary(
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "D:\Talking_head\MultiTalk-Code\venv\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: ("Could not find module 'OSMesa' (or one of its dependencies). Try using the full path with constructor syntax.", 'OSMesa', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main\demo_dir.py", line 24, in <module>
    import pyrender
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\osmesa.py", line 66, in GetCurrentContext
    function = self.OSMesa.OSMesaGetCurrentContext
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\osmesa.py", line 60, in OSMesa
    def OSMesa( self ): return self.GL
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\OpenGL\platform\osmesa.py", line 28, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "Could not find module 'OSMesa' (or one of its dependencies). Try using the full path with constructor syntax.", 'OSMesa', None)

**Comment by linhcentrio** [comment]
i search this: https://github.com/pal1000/mesa-dist-win

**Comment by mor-panjaya** [comment]
For me it was fixed after the following installations (see: [https://github.com/mmatl/pyrender/issues/32](https://github.com/mmatl/pyrender/issues/32)):
- sudo apt install freeglut3-dev
- sudo apt-get install libosmesa6-dev
