### ISSUE TITLE
on windows 10: OSError: Can't load tokenizer for 'facebook/wav2vec2-large-xlsr-53'

### ISSUE THREAD

**Issue by linhcentrio** [postech-ami/MultiTalk#5]
`(D:\Talking_head\MultiTalk-Code\venv) D:\Talking_head\MultiTalk-Code>scripts\demo.bat multi
Some weights of the model checkpoint at facebook/wav2vec2-large-xlsr-53 were not used when initializing Wav2Vec2Model: ['quantizer.weight_proj.bias', 'quantizer.codevectors', 'quantizer.weight_proj.weight', 'project_hid.weight', 'project_q.weight', 'project_hid.bias', 'project_q.bias']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
=> loading checkpoint 'checkpoints/stage2.pth.tar'
=> loaded checkpoint 'checkpoints/stage2.pth.tar'
Generating facial animation for demo/input\English_WTT5UTZQ9K8_8.wav...
Traceback (most recent call last):
  File "main\demo_dir.py", line 224, in <module>
    main()
  File "main\demo_dir.py", line 135, in main
    test(model, cfg.demo_wav_dir_path, save_folder, condition, subject)
  File "main\demo_dir.py", line 173, in test
    processor = Wav2Vec2Processor.from_pretrained(cfg.wav2vec2model_path)
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\transformers\models\wav2vec2\processing_wav2vec2.py", line 105, in from_pretrained
    tokenizer = Wav2Vec2CTCTokenizer.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "D:\Talking_head\MultiTalk-Code\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1708, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for 'facebook/wav2vec2-large-xlsr-53'. Make sure that:

- 'facebook/wav2vec2-large-xlsr-53' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'facebook/wav2vec2-large-xlsr-53' is the correct path to a directory containing relevant tokenizer files`

**Comment by HoustonHuff** [comment]
I've also run into an issue like this where I just can't load the model, and I'm not sure how to proceed.

The tokenizer and audio files for the /facebook/wav2vec2-large-xlsr-53 repo just aren't there; not even loading from a Colab environment seems to work, so it doesn't seem to be caused by my local machine setup. I found the Wav2Vec2FeatureExtractor class does seem to load the model rather than Wav2Vec2Processor, but those classes aren't interchangeable in the pipeline and simply swapping out the model with a tokenizer one like wav2vec2-large-960 doesn't seem right to do either.

**Comment by didncd** [comment]
Has this issue been resolved?
